// Local Host
GET http://localhost:5500/contacts
###
GET http://localhost:5500/contacts/62a7fcc40cf4af5858c7ce64
###
GET http://localhost:5500/contacts/62a80d8c0cf4af5858c7ce65
###
GET http://localhost:5500/contacts/62a80d8c0cf4af5858c7ce65
###

// Heroku
GET http://cse341-personal2brunst.herokuapp.com/contacts
###
GET http://cse341-personal2brunst.herokuapp.com/contacts/62a2d09e31c121c72b9ab008
###
GET http://cse341-personal2brunst.herokuapp.com/contacts/62a2d20531c121c72b9ab009
###
GET http://cse341-personal2brunst.herokuapp.com/contacts/62a2d65731c121c72b9ab00a
###

// Post 
POST http://localhost:5500/contacts
Content-Type: application/json

{
    "firstName":"Spencer",
    "lastName":"Hurd",
    "email":"spencer.ninja@gmail.com",
    "favoriteColor":"green",
    "birthday":"08/14/1989"
}

###
POST http://localhost:5500/contacts
Content-Type: application/json

{
    "firstName":"Brooke",
    "lastName":"Sanchez",
    "email":"b.sanchez@gmail.com",
    "favoriteColor":"yellow",
    "birthday":"05/15/1991"
}

###
POST http://localhost:5500/contacts
Content-Type: application/json

{
    "firstName":"Richard",
    "lastName":"Brunst",
    "email":"rbrunst@gmail.com",
    "favoriteColor":"blue",
    "birthday":"08/12/1990"
}

